version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: mypassword
      RAILS_MASTER_KEY: 79074ee543275087d0057ecaccd1953a

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    depends_on:
      - db
      - redis
    command: bash -c "bundle exec sidekiq"
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: mypassword
      RAILS_MASTER_KEY: 79074ee543275087d0057ecaccd1953a
      REDIS_URL: redis://redis:6379
